{% if theme.carousel.enable %}

    <iframe src="/html/carousel.html?from1={{theme.carousel.from1}}&img1={{theme.carousel.img1}}&from2={{theme.carousel.from2}}&img2={{theme.carousel.img2}}&from3={{theme.carousel.from3}}&img3={{theme.carousel.img3}}&from4={{theme.carousel.from4}}&img4={{theme.carousel.img4}}" width="65%" height="320px" style="border: 0px; overflow: hidden; border-radius: 10px;" scrolling="no"></iframe>

{% endif %}


