title:
  archive: Archive
  category: Category
  tag: Tag
  schedule: Schedule

author: Author

menu:
  home: Home
  archives: Archives
  categories: Categories
  tags: Tags
  about: About
  search: Search
  schedule: Schedule
  sitemap: Sitemap

sidebar:
  overview: Overview
  toc: Table of Contents

post:
  created: Post created
  modified: Post modified
  sticky: Sticky
  posted: Posted on
  in: In
  read_more: Read more
  untitled: Untitled
  toc_empty: This post does not have a Table of Contents
  visitors: Visitors
  wordcount: Words count in article
  min2read: Reading time

page:
  totally: Totally
  tags: tags

footer:
  powered: "Powered by %s"
  theme: Theme

counter:
  tag_cloud:
    zero: No tags
    one: 1 tag in total
    other: "%d tags in total"

  categories:
    zero: No categories
    one: 1 category in total
    other: "%d categories in total"

  archive_posts:
    zero: No posts.
    one: 1 post.
    other: "%d posts in total."

state:
  posts: posts
  pages: pages
  tags: tags
  categories: categories

cheers:
  um: Um..
  ok: OK
  nice: Nice
  good: Good
  great: Great
  excellent: Excellent

keep_on: Keep on posting.

symbol:
  comma: ', '
  period: '. '
